version: '3'

services:
  prometheus:   # docker run --restart=always --name prometheus -p 9090:9090 prom/prometheus:v2.27.1
    container_name: "prometheus"
    image: prom/prometheus:v2.27.1
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

